### ISSUE TITLE
implement viewing profile of a particular user

### ISSUE THREAD

**Issue by okieLoki** [developer-student-club-thapar/DSA-Portal-Backend#12]
GET /api/user/:leetcodeUsername

(Refer the readme file for more info)

**Comment by Manan-Sharma-5** [comment]
Would Like to Contribute to this issue.

**Comment by JhndaCoder** [comment]
> Would Like to Contribute to this issue.

Assigned

**Comment by Manan-Sharma-5** [comment]
Hi.. The issue has been completed and the pr is merged. THANKS
