### ISSUE TITLE
implement viewing all profiles stored in the database

### ISSUE THREAD

**Issue by Manan-Sharma-5** [developer-student-club-thapar/DSA-Portal-Backend#16]
GET /api/user/

(Refer the readme file for more info)

**Comment by Sky-De** [comment]
@Manan-Sharma-5 hi there , please assign this to me , i would like to work on this 
thanks

**Comment by Manan-Sharma-5** [comment]
Yes Sure.

**Comment by Sky-De** [comment]
@Manan-Sharma-5 hi again, i forked and took a look to your code , 
there is only two models 
what is your mean of **viewing all profiles** ?
do you mean getting all user whome exist in DB ? ( like => const allUsers = await User.find() then response  allUsers)

**Comment by Manan-Sharma-5** [comment]
So, we need to provide a response in the format 
[
  {
    "_id": "user_id1",
    "name": "John Doe",
    "leetcodeUserName": "john123",
    "solvedProblems": ["two-sum", "reverse-integer", "palindrome-number"]
  },
  {
    "_id": "user_id2",
    "name": "Alice Smith",
    "leetcodeUserName": "alice_smith",
    "solvedProblems": ["reverse-integer", "binary-search"]
  },
  // Other users...
]
From the user model.

Edit: Yes, it should include all the users stored in the database with the given data
