### ISSUE TITLE
implement auth system

### ISSUE THREAD

**Issue by okieLoki** [developer-student-club-thapar/DSA-Portal-Backend#6]
Currently anyone can get the data from the database, we want to implement an auth system which would require email id and password (hashed using bcrypt js) such that only a logged in user can perform pull data from the database.

Tasks: 
- Modify POST /api/auth/register and add a password field 
- Implement POST /api/auth/login 
- Make use of bcrypt js and jwt
- Create an auth middleware to verify the jwt (passed as a Bearer token)
- Add that auth middleware in all other existing routes

**Comment by Manan-Sharma-5** [comment]
I would like to work on this issue...
